### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by hrj** [macroing/Dayflower-Path-Tracer#1]
Hi,

Interesting project!

The README says "This project currently only works on Windows machines."

I was able to run it on Linux too, but it doesn't use OpenCL and hence is very slow.

How to add support for Linux? Which version of Aparapi are you using? I found atleast 3 variants:

* Original AMD project: https://github.com/aparapi/aparapi/
* https://github.com/Syncleus/aparapi/
* https://github.com/macroing/aparapi

thanks!

**Comment by macroing** [comment]
Hi hrj,

Thank you for showing interest in my project!

I'm using the version that is linked to in the README file. That is, the one on my GitHub page (https://github.com/macroing/aparapi), which is based on an earlier version of the original Aparapi project.

To add support for Linux, you'd have to compile the Aparapi project for Linux. Or, you could change it to the original Aparapi project and update the code in org.dayflower.pathtracer.kernel.RendererKernel.java that uses my custom code for Aparapi. I implemented a bunch of methods in that version of Aparapi, but I think I only use one or so in this project.

**Comment by hrj** [comment]
Thanks @macroing for getting back. I did a quick attempt at compiling `macroing/aparapi`, but it failed with this output:

```
Buildfile: /home/user/aparapi/build.xml

clean:

clean:

clean:

clean:

clean:

clean:

clean:

clean:

clean:

clean:
     [echo] OS Name:    	Linux
     [echo] OS Version: 	4.10.0-42-generic
     [echo] OS Arch:    	amd64
     [echo] Java Version:   	1.8.0_131

clean:

clean:

clean:

clean:

clean:
     [echo] This project REQUIRES NBODY to be built first!!!

clean:
     [echo] OS Name:    Linux
     [echo] OS Version: 4.10.0-42-generic
     [echo] OS Arch:    amd64

clean:
     [echo] OS Name:    Linux
     [echo] OS Version: 4.10.0-42-generic
     [echo] OS Arch:    amd64

clean:
     [echo] OS Name:    Linux
     [echo] OS Version: 4.10.0-42-generic
     [echo] OS Arch:    amd64
     [echo] Java Ver:   1.8.0_131
     [echo] 
     [echo]       Note: Since AMD APP SDK 2.9 you can have multiple versions installed/co-exist on same machine, 
     [echo]       so AMD introduced a completely new naming convention for their installation directories
     [echo]       For example C:/Program Files/AMD APP SDK/2.9-1
     [echo]    

init:
     [echo] amd.app.sdk.dir ${amd.app.sdk.dir}
     [echo]  intel.app.sdk.dir ${intel.app.sdk.dir}
     [echo]  freebsd.app.sdk.dir ${freebsd.app.sdk.dir}
     [echo]  vendor.name ${vendor.name}
     [echo] app.sdk.dir ${app.sdk.dir}
     [echo]  msvc.dir ${msvc.dir}
     [echo]  msvc.sdk.dir ${msvc.sdk.dir}

check:

BUILD FAILED
/home/user/aparapi/build.xml:40: The following error occurred while executing this line:
/home/user/aparapi/com.amd.aparapi.jni/build.xml:486: Error:
         
         
         You will need to edit com.amd.aparapi.jni/build.xml to compile aparapi JNI code

         You need to set app.sdk.dir to point to the location where OpenCL SDK is installed

```

Looks like it needs some OpenCL SDK to be installed and I have no idea what that means.
Any hints appreciated!

**Comment by macroing** [comment]
Yes, you're correct, you need some OpenCL SDK to compile it. The natives from the SDK are required. You can download the AMD APP SDK for example. I use that one.

I tried to port the project back to the original Aparapi, but I was not successful. Some unsatisfied link error occurred and I don't know why. I included the natives as part of the library in Eclipse, but that didn't change anything. The original project has only one release, which is from 2014, so maybe that has something to do with it.

If you try the old Aparapi yourself, the only thing you need to change, is to add the following code to ``org.dayflower.pathtracer.kernel.AbstractKernel.java``:
```java
public final float asinpi(final float a) {
    return asin(a) * PI_RECIPROCAL;
}
```
