### ISSUE TITLE
Very low frame rate on 2Ghz Intel Windows 10 Nvidia GTX 1660 Ti

### ISSUE THREAD

**Issue by antic-ml** [macroing/Dayflower-Path-Tracer#2]
I get a really low frame rate of 1 frame per second when using Dayflower on a 2 Ghz Intel Windows 10 Nvidia GTX 1660 Ti.

**Comment by macroing** [comment]
Thank you for trying my renderer, @antic-ml!

Are you running the renderer with the default settings? The default scene is called "Material_Showcase_Scene".

When I run the renderer with the default settings and do not walk around, my FPS is around 47. If I turn off normal mapping and the sun, my FPS is around 55.

The other scenes, with a lot more geometric primitives (triangle meshes), will unfortunately cause a major decrease in performance. For these scenes I get an FPS between 1 and 10, depending on which scene it is. This performance decrease is something I've been looking for a solution to for a long time, but not found one yet. I suspect there is a problem with my BVH implementation.

This renderer uses OpenCL and not CUDA. But I assume you have support for OpenCL.

What version of Java are you using? I use Java 8, so I have only tested it with Java 8. The reason I never upgraded my Java version is because I cannot guarantee it will continue to work. If I remember correctly, Aparapi uses "sun.misc.Unsafe".

Do you get any warnings or other information in your console?

**Comment by antic-ml** [comment]
Yes I am running the renderer with the default settings. 

I get the following printed to the console when I run the renderer:
``
Oct 22, 2019 11:21:15 AM com.amd.aparapi.internal.opencl.OpenCLLoader <clinit>
SEVERE: Check your environment. Failed to load aparapi native library aparapi_x86 or possibly failed to locate opencl native library (opencl.dll/opencl.so). Ensure that both are in your PATH (windows) or in LD_LIBRARY_PATH (linux).
``

I think the problem I am getting such a low frame rate is because the kernel is falling back to Java threads as a result of Aparapi being unable to load the native library. OpenCl is installed on my machine and working correctly because I have been using Aparapi in another project, and it works just fine. 

I am using your run.bat file to execute the renderer and the files that Aparapi needs are in the lib directory.

**Comment by macroing** [comment]
Yes, Aparapi automatically falls back to Java Thread Pool-mode (JTP) when it cannot run as intended. It looks like that is what has happened.

In your own project, do you use any other file than "aparapi_x86_64.dll"? When I compiled Aparapi, I only compiled it for 64-bit. It could be that you require the 32-bit version?

**Comment by antic-ml** [comment]
I am using a 64-bit machine.

I'll investigate a little further and see if I can resolve the issue.

**Comment by antic-ml** [comment]
It just occurred to me... does Aparapi expect the dll to be inside the JAR? They could be loading the library with a path. For example:
``static {
    try {
    	System.load("com/aparapi/path/aparapi_x86_64.dll");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load.\n" + e);
      System.exit(1);
    }
``

Could that be it? If so perhaps you could solve the problem by extracting Aparapi into the Dayflower Jar?

**Comment by macroing** [comment]
Okay, so we're both using 64-bit systems. This seems pretty weird.

I'm trying to locate where in the Aparapi source code the libraries are loaded.

I've never tried putting a .jar file in another .jar file. Does that even work?

**Comment by antic-ml** [comment]
Haha. No, don't put the Aparapi JAR inside the Dayflower Jar - that wouldn't make any sense.

**Comment by antic-ml** [comment]
The following link shows a source file called NativeLoader.java which Aparapi uses to load the DLL:
[https://github.com/Syncleus/aparapi-jni/blob/master/src/main/java/com/aparapi/natives/NativeLoader.java](url) It appears that the DLL is loaded from the JAR file and not from a file system directory. However, the link to the source above is for version 1.10.0 of Aparapi and I believe you are using an earlier version. Hope this is of some help.

--Mario

**Comment by macroing** [comment]
Then I probably misunderstood what you meant. ;)

Did you write the link? I cannot see it.

Anyway, I searched through the entire project for "System.load" (using a search tool I've written in the past), but I couldn't find any occurrences. However, I found some documentation that shows how it should be set up. As far as I can tell, that's also the way I set it up for Dayflower. The class-path is specified in the .jar file.

The documentation can be found here:
https://github.com/macroing/aparapi/blob/master/doc/LIbraryAgentDuality.md

The version of Aparapi that I'm using is an extended version of the original one, with five commits ahead of the original. Is the one you're referring to the one provided by Syncleus?

**Comment by macroing** [comment]
Now I see your link. Previously it was just "NativeLoader.java".

**Comment by macroing** [comment]
When I remove the native library I get the following:

`Failed to load aparapi native library aparapi_x86_64 or possibly failed to locate opencl native library (opencl.dll/opencl.so).`

In my case it says it fails to load "aparapi_x86_64", whereas in your case it fails to load "aparapi_x86". This suggests that you require the "aparapi_x86.dll" file. This file has not been compiled, just as I mentioned previously. Maybe the 32-bits and 64-bits in this case refers to what the GPU requires and not what the system actually uses.

When I run Aparapi I can use double types. The default is that you can only use float types. This could have something to do with that as well. Have you ever tried to use double types when using Aparapi?

**Comment by antic-ml** [comment]
That could be it. I tried downloading the Aparapi 1.10.0 JAR file and extracting the aparapi_x86.dll from it and putting it in Dayflower's lib directory, but when I ran Dayflower it gave me the same warning that it couldn't load the DLL. Perhaps there are different versions of the DLL for different versions of Aparapi? It is difficult to tell which version of Aparapi you are using in Dayflower. Perhaps it would be worthwhile making a new release of Dayflower and including both 64 bit and 32 bit DLLs?

I tried using a 64 bit double array in a Kernel and the JVM just hung. It would seem that I require the 32-bit version.

**Comment by macroing** [comment]
My version of Aparapi is the one provided on my GitHub account.
https://github.com/macroing/aparapi

I havn't managed to build any other version of it than the 64-bit version.

Maybe you could try extracting this version? It's the release of the one I based it on, if I remember correctly.
https://github.com/aparapi/aparapi/releases/download/1.0.0-SNAPSHOT/dist_windows_x86.zip
